MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMhhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMhhhmMMMMMMMMMMMMMMMMMMMMMMMMMNdhhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMhhhhdMMMMMMMMMMMMMMMMMMMMMMMNhhhhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMhhhhhhNMMMMMMMMMMMMMMMMMMMMNhhhhhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMdhhhhhhNMMMMMMMMMMMMMMMMMMmhhhhhhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMdhhhhhhhmMMMMMMMMMMMMMMMMmhhhhhhhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMdhhhhhhhhmMMMMMMMMMMMMMMdhhhhhhhhNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMdhhhhhhhhhdMMMMMMMMMMMNdhhhhhhhhdMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNmdhhhhhhhdNMMMMMMMMNdhhhhhhdmNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhhhNMMMMMMNhhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhhhmMMMMmhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdmMMmdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

***************************************************************************
#  ▓█████▓██   ██▓▓█████    ▒██   ██▒ ██▓███   ██▓     ▒█████   ██▓▄▄▄█████▓
#  ▓█   ▀ ▒██  ██▒▓█   ▀    ▒▒ █ █ ▒░▓██░  ██▒▓██▒    ▒██▒  ██▒▓██▒▓  ██▒ ▓▒
#  ▒███    ▒██ ██░▒███      ░░  █   ░▓██░ ██▓▒▒██░    ▒██░  ██▒▒██▒▒ ▓██░ ▒░
#  ▒▓█  ▄  ░ ▐██▓░▒▓█  ▄     ░ █ █ ▒ ▒██▄█▓▒ ▒▒██░    ▒██   ██░░██░░ ▓██▓ ░ 
#  ░▒████▒ ░ ██▒▓░░▒████▒   ▒██▒ ▒██▒▒██▒ ░  ░░██████▒░ ████▓▒░░██░  ▒██▒ ░ 
#  ░░ ▒░ ░  ██▒▒▒ ░░ ▒░ ░   ▒▒ ░ ░▓ ░▒▓▒░ ░  ░░ ▒░▓  ░░ ▒░▒░▒░ ░▓    ▒ ░░   
#   ░ ░  ░▓██ ░▒░  ░ ░  ░   ░░   ░▒ ░░▒ ░     ░ ░ ▒  ░  ░ ▒ ▒░  ▒ ░    ░    
#     ░   ▒ ▒ ░░     ░       ░    ░  ░░         ░ ░   ░ ░ ░ ▒   ▒ ░  ░      
#     ░  ░░ ░        ░  ░    ░    ░               ░  ░    ░ ░   ░           
#         ░ ░                                                               
#   ▄▄▄▄ ▓██   ██▓    ▄▄▄      ███▄    █ ▓█████▄  ██▀███   ▒█████  ▒██   ██▒
#  ▓█████▄▒██  ██▒   ▒████▄    ██ ▀█   █ ▒██▀ ██▌▓██ ▒ ██▒▒██▒  ██▒▒▒ █ █ ▒░
#  ▒██▒ ▄██▒██ ██░   ▒██  ▀█▄ ▓██  ▀█ ██▒░██   █▌▓██ ░▄█ ▒▒██░  ██▒░░  █   ░
#  ▒██░█▀  ░ ▐██▓░   ░██▄▄▄▄██▓██▒  ▐▌██▒░▓█▄   ▌▒██▀▀█▄  ▒██   ██░ ░ █ █ ▒ 
#  ░▓█  ▀█▓░ ██▒▓░    ▓█   ▓██▒██░   ▓██░░▒████▓ ░██▓ ▒██▒░ ████▓▒░▒██▒ ▒██▒
#  ░▒▓███▀▒ ██▒▒▒     ▒▒   ▓▒█░ ▒░   ▒ ▒  ▒▒▓  ▒ ░ ▒▓ ░▒▓░░ ▒░▒░▒░ ▒▒ ░ ░▓ ░
#  ▒░▒   ░▓██ ░▒░      ▒   ▒▒ ░ ░░   ░ ▒░ ░ ▒  ▒   ░▒ ░ ▒░  ░ ▒ ▒░ ░░   ░▒ ░
#   ░    ░▒ ▒ ░░       ░   ▒     ░   ░ ░  ░ ░  ░   ░░   ░ ░ ░ ░ ▒   ░    ░  
#   ░     ░ ░              ░  ░        ░    ░       ░         ░ ░   ░    ░  
#        ░░ ░                             ░                                 

***************************************************************************
***************************************************************************


boot nousb          - to turn off USB if not used and it causes problems
boot vga=ask        - if you have problems with the videomode
boot nodrivers      - skip automatic disk driver loading

